[project]
name = "20q"
version = "0.1.0"
description = "A 20q.net thingy using a headless browser via playwright"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytest-playwright>=0.7.0",
]
